blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls')),
    path('accounts/login/', views.LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    path('accounts/logout/', views.LogoutView.as_view(template_name='registration/login.html'), name='logout'),
    # path('accounts/login/', views.login, name='login'),
    # path('accounts/logout/', views.logout, name='logout', kwargs={'next_page': '/'}),
]

blog/blog_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'blog_app'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name = 'about'),
    path('', views.PostListView.as_view(), name = 'post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name = 'post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name = 'add_comment_to_post'),
    path('comment/<int:pk>/approve', views.comment_approve, name ='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
]

blog/blog_app/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    author =  models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("blog_app:post_detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    #how to link to posts
    post = models.ForeignKey('blog_app.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("blog_app:post_list")

    def __str__(self):
        return self.text

blog/blog_app/forms.py
from django import forms
from blog_app.models import Comment, Post

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('author', 'title', 'text')

    #widgets for styling by giving them css classes connect widgets to css styling
        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }



class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('author', 'text')

        widgets = {
            'author': forms.TextInput(attrs={'class':'textinputclass'}),
            'text': forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

blog/blog_app/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.utils import timezone
from django.views.generic import TemplateView, ListView, DetailView, CreateView, DeleteView, UpdateView
from blog_app.models import Post, Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from blog_app.forms import PostForm, CommentForm
from django.urls import reverse_lazy

# Create your views here.

class AboutView(TemplateView):
    template_name = 'blog_app/about.html'

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte = timezone.now()).order_by('-published_date')
        #__lte is less than or equal to (it's a lookuptype for field queries. format is field__lookuptype)
        #- published makes it descending

class PostDetailView(DetailView):
    context_object_name = 'post_detail'
    model = Post
    template_name = 'blog_app/post_detail.html'

class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog_app/post_detail.html'
    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog_app/post_detail.html'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog_app:post_list')

class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    template_name = 'blog_app/post_draft_list.html'
    model = Post
    context_object_name = 'drafts'


    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('create_date')

############
############

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.save()
            return redirect('blog_app:post_detail', pk=post.pk)
    else:
        form = CommentForm
    return render(request, 'blog_app/comment_form.html', {'form':form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog_app:post_detail', pk = comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog_app:post_detail', pk=post_pk)

@login_required
def post_publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('blog_app:post_detail', pk=pk)

blog/blog_app/templates/blog_app/about.html
{% extends 'blog_app/base.html' %}

{% block content %}

<div class="jumbotron">
  <h1>Hi, I am Jervis</h1>
</div>

{% endblock %}

blog/blog_app/templates/blog_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Blog</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Playfair+Display&display=swap" rel="stylesheet">

  </head>
  <body class='loader'>
    <nav class="navbar navbar-expand-lg navbar-light bg-light techfont custom-navbar">
      <a class="navbar-brand bigbrand" href="{% url 'blog_app:post_list' %}"> My Blog </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="nav navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog_app:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.github.com">Github</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com">LinkedIn</a>
          </li>
        </ul>
        <ul class="nav navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog_app:post_new' %}">New Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog_app:post_draft_list' %}">Drafts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
          </li>
          <li class="nav-item">
            <a class="nav-link">Welcome: {{user.username}}</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="content container">
      <div class="row">
        <div class="col-md-8">
          <div class="blog_posts">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>


  </body>
</html>

blog/blog_app/templates/blog_app/comment_form.html
{% extends 'blog_app/base.html' %}

{% block content %}

<h1>New Comment</h1>
<form class="post-form" method="POSt">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class='save btn btn-default'>Post Comment</button>
</form>
<script type="text/javascript">
  var editor = new MediumEditor(".editable");
</script>

{%endblock%}

blog/blog_app/templates/blog_app/post_confirm_delete.html
{% extends 'blog_app/base.html' %}
{% block content %}

<form method="POST">
  {% csrf_token %}
  <p>Are you sure you want to delete {{ object }}</p>
  <input type="submit" class = "btn btn-danger" value="Confirm">

</form>

{%endblock%}

blog/blog_app/templates/blog_app/post_detail.html
{% extends 'blog_app/base.html' %}

{% block content %}

<h1 class='posttitle loader'>{{object.title}}</h1>

{% if object.published_date %}

<div class="date postdate">
  {{object.published_date}}
</div>

{% else %}

<a href="{%url 'blog_app:post_publish' pk=object.pk %}" class = 'btn btn-primary'>Publish</a>
{% endif %}

<p class='postcontent'> {{object.text|safe|linebreaksbr }}</p>

{% if user.is_authenticated %}
 <a href="{% url 'blog_app:post_edit' pk=object.pk %}" class='btn btn-primary'>Edit</a>
 <a href="{% url 'blog_app:post_remove' pk=object.pk %}" class='btn btn-primary'>Remove</a>
{% endif %}

<hr>
<a href="{% url 'blog_app:add_comment_to_post' pk=object.pk %}" class='btn btn-primary btn-comment'>Add comment</a>

<div class="container">
  {% for comment in object.comments.all %}
  <br>
  {% if user.is_authenticated or comment.approved_comment %}
  {{comment.create_date}}
  {%if not comment.approved_comment %}
  <a href="{% url 'blog_app:comment_approve' pk=comment.pk %}" class='btn btn-default'>Approve</a>
  <a href="{% url 'blog_app:comment_remove' pk=comment.pk %}" class='btn btn-default'>Remove</a>
  {% endif %}
  <p>{{comment.text|safe|linebreaksbr}}</p>
  <p>Posted by: {{comment.author}}</p>
  {% endif %}

  {% empty %}

  <p>No comment</p>
  {% endfor %}



</div>

{%endblock%}

blog/blog_app/templates/blog_app/post_draft_list.html
{% extends 'blog_app/base.html' %}

{% block content %}

{% for post in drafts %}
<div class="post container">
  <h1><a href="{% url 'blog_app:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
  <p class = 'date'>Created: {{post.create_date | date:"d-m-Y"}}</p>
  <p>{{post.text|safe|linebreaksbr}}</p>
</div>

{% endfor %}

{%endblock%}

blog/blog_app/templates/blog_app/post_form.html
{% extends 'blog_app/base.html' %}
{% block content %}

<h1>New Post</h1>

<form class="post-form" method="POST">
  {% csrf_token %}

  {{form.as_p}}

  <button type="submit" class="save btn btn-default">Submit</button>

</form>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

blog/blog_app/templates/blog_app/post_list.html
{% extends 'blog_app/base.html' %}

{% block content %}

<div class="centerstage">

  {% for post in post_list %}
  <div class="post">
    <h1><a href="{% url 'blog_app:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
    <div class="date">
      <p>Published on: {{post.published_date | date:"d-m-Y"}}</p>
    </div>
    <a href="{% url 'blog_app:post_detail' pk=post.pk%}">Comments: {{post.approve_comments.count}}</a>

  </div>
  {% endfor %}

</div>


{% endblock %}